name       : python3-decorator
version    : 4.1.2
release    : 2
source     :
    - https://pypi.python.org/packages/bb/e0/f6e41e9091e130bf16d4437dabbac3993908e4d6485ecbc985ef1352db94/decorator-4.1.2.tar.gz : 7cb64d38cb8002971710c8899fbdfb859a23a364b7c99dab19d1f719c2ba16b5
license    : BSD-3-Clause
component  : programming.python
summary    : Better living through Python with decorators
description: |
    Better living through Python with decorators
builddeps  :
    - pkgconfig(python-3.5)
build      : |
    %python3_setup
install    : |
    %python3_install
